# Generated by Django 3.2.7 on 2021-12-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('slug', models.SlugField(max_length=70, unique=True)),
                ('img', models.ImageField(upload_to='productcategory')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('desc', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='productcategory')),
                ('url', models.URLField()),
                ('price', models.IntegerField()),
                ('pub_date', models.DateField()),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category')),
            ],
        ),
    ]
